"""Adds FK

Revision ID: f2cc126109c4
Revises: 3ae01bc0b309
Create Date: 2023-08-08 20:19:02.151336

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "f2cc126109c4"
down_revision = "3ae01bc0b309"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("brand_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "product", "brand", ["brand_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "brand_id")
    # ### end Alembic commands ###
